/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccountSettingsTemplateRequest : Request body format for Account Settings Template REST requests. When creating a template properties account_id and name are mandatory.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountSettingsTemplateRequest {
    /// ID of the account where the template resides.
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// The name of the trusted profile template. This is visible only in the enterprise account.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The description of the trusted profile template. Describe the template for enterprise account users.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "account_settings", skip_serializing_if = "Option::is_none")]
    pub account_settings: Option<Box<models::AccountSettingsComponent>>,
}

impl AccountSettingsTemplateRequest {
    /// Request body format for Account Settings Template REST requests. When creating a template properties account_id and name are mandatory.
    pub fn new() -> AccountSettingsTemplateRequest {
        AccountSettingsTemplateRequest {
            account_id: None,
            name: None,
            description: None,
            account_settings: None,
        }
    }
}
