/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionControls {
    #[serde(rename = "identities", skip_serializing_if = "Option::is_none")]
    pub identities: Option<Box<models::ActionControlsIdentities>>,
    #[serde(rename = "rules")]
    pub rules: Box<models::ActionControlsIdentities>,
    #[serde(rename = "policies")]
    pub policies: Box<models::ActionControlsIdentities>,
}

impl ActionControls {
    pub fn new(rules: models::ActionControlsIdentities, policies: models::ActionControlsIdentities) -> ActionControls {
        ActionControls {
            identities: None,
            rules: Box::new(rules),
            policies: Box::new(policies),
        }
    }
}

