/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateProfileLinkRequestLink : Link details
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProfileLinkRequestLink {
    /// The CRN of the compute resource
    #[serde(rename = "crn")]
    pub crn: String,
    /// The compute resource namespace, only required if cr_type is IKS_SA or ROKS_SA
    #[serde(rename = "namespace")]
    pub namespace: String,
    /// Name of the compute resource, only required if cr_type is IKS_SA or ROKS_SA
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl CreateProfileLinkRequestLink {
    /// Link details
    pub fn new(crn: String, namespace: String) -> CreateProfileLinkRequestLink {
        CreateProfileLinkRequestLink {
            crn,
            namespace,
            name: None,
        }
    }
}

