/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProfileLinkRequest {
    /// Optional name of the Link
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The compute resource type. Valid values are VSI, IKS_SA, ROKS_SA
    #[serde(rename = "cr_type")]
    pub cr_type: String,
    #[serde(rename = "link")]
    pub link: Box<models::CreateProfileLinkRequestLink>,
}

impl CreateProfileLinkRequest {
    pub fn new(cr_type: String, link: models::CreateProfileLinkRequestLink) -> CreateProfileLinkRequest {
        CreateProfileLinkRequest {
            name: None,
            cr_type,
            link: Box::new(link),
        }
    }
}

