/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateTrustedProfileRequest : Input body parameters for the Create trusted profile V1 REST request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTrustedProfileRequest {
    /// Name of the trusted profile. The name is checked for uniqueness. Therefore trusted profiles with the same names can not exist in the same account.
    #[serde(rename = "name")]
    pub name: String,
    /// The optional description of the trusted profile. The 'description' property is only available if a description was provided during creation of trusted profile.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The account ID of the trusted profile.
    #[serde(rename = "account_id")]
    pub account_id: String,
    /// The email of the trusted profile.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
}

impl CreateTrustedProfileRequest {
    /// Input body parameters for the Create trusted profile V1 REST request.
    pub fn new(name: String, account_id: String) -> CreateTrustedProfileRequest {
        CreateTrustedProfileRequest {
            name,
            description: None,
            account_id,
            email: None,
        }
    }
}

