/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MfaEnrollments {
    /// currently effective mfa type i.e. id_based_mfa or account_based_mfa
    #[serde(rename = "effective_mfa_type")]
    pub effective_mfa_type: String,
    #[serde(rename = "id_based_mfa", skip_serializing_if = "Option::is_none")]
    pub id_based_mfa: Option<models::IdBasedMfaEnrollment>,
    #[serde(rename = "account_based_mfa", skip_serializing_if = "Option::is_none")]
    pub account_based_mfa: Option<models::AccountBasedMfaEnrollment>,
}

impl MfaEnrollments {
    pub fn new(effective_mfa_type: String) -> MfaEnrollments {
        MfaEnrollments {
            effective_mfa_type,
            id_based_mfa: None,
            account_based_mfa: None,
        }
    }
}
