/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MfaEnrollmentTypeStatus {
    /// Describes whether the enrollment type is required.
    #[serde(rename = "required")]
    pub required: bool,
    /// Describes whether the enrollment type is enrolled.
    #[serde(rename = "enrolled")]
    pub enrolled: bool,
}

impl MfaEnrollmentTypeStatus {
    pub fn new(required: bool, enrolled: bool) -> MfaEnrollmentTypeStatus {
        MfaEnrollmentTypeStatus {
            required,
            enrolled,
        }
    }
}

