/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PolicyTemplateReference : Metadata for external access policy
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PolicyTemplateReference {
    /// ID of Access Policy Template
    #[serde(rename = "id")]
    pub id: String,
    /// Version of Access Policy Template
    #[serde(rename = "version")]
    pub version: String,
}

impl PolicyTemplateReference {
    /// Metadata for external access policy
    pub fn new(id: String, version: String) -> PolicyTemplateReference {
        PolicyTemplateReference { id, version }
    }
}
