/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileLinkList {
    /// List of links to a trusted profile
    #[serde(rename = "links")]
    pub links: Vec<models::ProfileLink>,
}

impl ProfileLinkList {
    pub fn new(links: Vec<models::ProfileLink>) -> ProfileLinkList {
        ProfileLinkList { links }
    }
}
