/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileIdentitiesUpdateRequest {
    /// List of identities that can assume the trusted profile
    #[serde(rename = "identities", skip_serializing_if = "Option::is_none")]
    pub identities: Option<Vec<models::ProfileIdentityRequest>>,
}

impl ProfileIdentitiesUpdateRequest {
    pub fn new() -> ProfileIdentitiesUpdateRequest {
        ProfileIdentitiesUpdateRequest {
            identities: None,
        }
    }
}

