/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfileIdentitiesResponse {
    /// Entity tag of the profile identities response
    #[serde(rename = "entity_tag", skip_serializing_if = "Option::is_none")]
    pub entity_tag: Option<String>,
    /// List of identities
    #[serde(rename = "identities", skip_serializing_if = "Option::is_none")]
    pub identities: Option<Vec<models::ProfileIdentityResponse>>,
}

impl ProfileIdentitiesResponse {
    pub fn new() -> ProfileIdentitiesResponse {
        ProfileIdentitiesResponse {
            entity_tag: None,
            identities: None,
        }
    }
}

