/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportReference {
    /// Reference for the report to be generated.
    #[serde(rename = "reference")]
    pub reference: String,
}

impl ReportReference {
    pub fn new(reference: String) -> ReportReference {
        ReportReference {
            reference,
        }
    }
}

