/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TemplateAssignmentResponseResource : Overview of resources assignment per target account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TemplateAssignmentResponseResource {
    /// Target account where the IAM resource is created.
    #[serde(rename = "target")]
    pub target: String,
    #[serde(rename = "profile", skip_serializing_if = "Option::is_none")]
    pub profile: Option<models::TemplateAssignmentResponseResourceDetail>,
    #[serde(rename = "account_settings", skip_serializing_if = "Option::is_none")]
    pub account_settings: Option<models::TemplateAssignmentResponseResourceDetail>,
    /// Policy resource(s) included only for trusted profile assignments with policy references.
    #[serde(rename = "policy_template_refs", skip_serializing_if = "Option::is_none")]
    pub policy_template_refs: Option<Vec<models::TemplateAssignmentResponseResourceDetail>>,
}

impl TemplateAssignmentResponseResource {
    /// Overview of resources assignment per target account
    pub fn new(target: String) -> TemplateAssignmentResponseResource {
        TemplateAssignmentResponseResource {
            target,
            profile: None,
            account_settings: None,
            policy_template_refs: None,
        }
    }
}

