/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrustedProfileTemplateList {
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Box<models::ResponseContext>>,
    /// The offset of the current page.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    /// Optional size of a single page.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Link to the first page.
    #[serde(rename = "first", skip_serializing_if = "Option::is_none")]
    pub first: Option<String>,
    /// Link to the previous available page. If 'previous' property is not part of the response no previous page is available.
    #[serde(rename = "previous", skip_serializing_if = "Option::is_none")]
    pub previous: Option<String>,
    /// Link to the next available page. If 'next' property is not part of the response no next page is available.
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
    /// List of Profile Templates based on the query paramters and the page size. The profile_templates array is always part of the response but might be empty depending on the query parameter values provided.
    #[serde(rename = "profile_templates")]
    pub profile_templates: Vec<models::TrustedProfileTemplateResponse>,
}

impl TrustedProfileTemplateList {
    pub fn new(
        profile_templates: Vec<models::TrustedProfileTemplateResponse>,
    ) -> TrustedProfileTemplateList {
        TrustedProfileTemplateList {
            context: None,
            offset: None,
            limit: None,
            first: None,
            previous: None,
            next: None,
            profile_templates,
        }
    }
}
