/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TrustedProfilesList : Response body format for the List trusted profiles V1 REST request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrustedProfilesList {
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Box<models::ResponseContext>>,
    /// The offset of the current page.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    /// Optional size of a single page. Default is 20 items per page. Valid range is 1 to 100
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    /// Link to the first page.
    #[serde(rename = "first", skip_serializing_if = "Option::is_none")]
    pub first: Option<String>,
    /// Link to the previous available page. If 'previous' property is not part of the response no previous page is available.
    #[serde(rename = "previous", skip_serializing_if = "Option::is_none")]
    pub previous: Option<String>,
    /// Link to the next available page. If 'next' property is not part of the response no next page is available.
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
    /// List of trusted profiles
    #[serde(rename = "profiles")]
    pub profiles: Vec<models::TrustedProfile>,
}

impl TrustedProfilesList {
    /// Response body format for the List trusted profiles V1 REST request.
    pub fn new(profiles: Vec<models::TrustedProfile>) -> TrustedProfilesList {
        TrustedProfilesList {
            context: None,
            offset: None,
            limit: None,
            first: None,
            previous: None,
            next: None,
            profiles,
        }
    }
}
