/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdatePreferenceRequest : Input body parameters for the update preference request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePreferenceRequest {
    /// contains a string value of the preference. only one value property is set, either 'value_string' or 'value_list_of_strings' is present.
    #[serde(rename = "value_string")]
    pub value_string: String,
    /// contains a list of string values of the preference. only one value property is set, either 'value_string' or 'value_list_of_strings' is present.
    #[serde(rename = "value_list_of_strings", skip_serializing_if = "Option::is_none")]
    pub value_list_of_strings: Option<Vec<String>>,
}

impl UpdatePreferenceRequest {
    /// Input body parameters for the update preference request.
    pub fn new(value_string: String) -> UpdatePreferenceRequest {
        UpdatePreferenceRequest {
            value_string,
            value_list_of_strings: None,
        }
    }
}

