/*
 * Global Search
 *
 * Search for resources with the global and shared resource properties repository that is integrated in the IBM Cloud platform. The search repository stores and searches cloud resources attributes, which categorize or classify resources. A resource is a physical or logical component that can be created or reserved for an application or service instance. They are owned by resource providers, such as IBM Kubernetes Service, or resource controller in IBM Cloud. Resources are uniquely identified by a Cloud Resource Name (CRN) or by an IMS ID. The properties of a resource include tags and system properties. Both properties are defined in an IBM Cloud billing account, and span across many regions.
 *
 * The version of the OpenAPI document: 2.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CatalogCategory : A Global catalog category
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogCategory {
    /// The category identifier
    #[serde(rename = "id")]
    pub id: String,
    /// The category display name in the selected language
    #[serde(rename = "display_name")]
    pub display_name: String,
    /// The category tags
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    /// The services that belong to the category
    #[serde(rename = "services")]
    pub services: Vec<models::CatalogCategoryService>,
    /// The category subcategories
    #[serde(rename = "children", skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<models::CatalogCategoryChild>>,
}

impl CatalogCategory {
    /// A Global catalog category
    pub fn new(
        id: String,
        display_name: String,
        tags: Vec<String>,
        services: Vec<models::CatalogCategoryService>,
    ) -> CatalogCategory {
        CatalogCategory {
            id,
            display_name,
            tags,
            services,
            children: None,
        }
    }
}
