/*
 * Global Search
 *
 * Search for resources with the global and shared resource properties repository that is integrated in the IBM Cloud platform. The search repository stores and searches cloud resources attributes, which categorize or classify resources. A resource is a physical or logical component that can be created or reserved for an application or service instance. They are owned by resource providers, such as IBM Kubernetes Service, or resource controller in IBM Cloud. Resources are uniquely identified by a Cloud Resource Name (CRN) or by an IMS ID. The properties of a resource include tags and system properties. Both properties are defined in an IBM Cloud billing account, and span across many regions.
 *
 * The version of the OpenAPI document: 2.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TermsAggregation : The aggregation request, which is based on terms (aka values) stored in fields: e.g. `us-south`, `eu-gb-1` stored in the `region` field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TermsAggregation {
    #[serde(rename = "terms")]
    pub terms: Box<models::TermsAggregationTerms>,
}

impl TermsAggregation {
    /// The aggregation request, which is based on terms (aka values) stored in fields: e.g. `us-south`, `eu-gb-1` stored in the `region` field.
    pub fn new(terms: models::TermsAggregationTerms) -> TermsAggregation {
        TermsAggregation {
            terms: Box::new(terms),
        }
    }
}
