/*
 * Global Search
 *
 * Search for resources with the global and shared resource properties repository that is integrated in the IBM Cloud platform. The search repository stores and searches cloud resources attributes, which categorize or classify resources. A resource is a physical or logical component that can be created or reserved for an application or service instance. They are owned by resource providers, such as IBM Kubernetes Service, or resource controller in IBM Cloud. Resources are uniquely identified by a Cloud Resource Name (CRN) or by an IMS ID. The properties of a resource include tags and system properties. Both properties are defined in an IBM Cloud billing account, and span across many regions.
 *
 * The version of the OpenAPI document: 2.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`get_catalog_categories`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCatalogCategoriesError {
    Status401(models::Errors),
    Status429(String),
    Status500(models::Errors),
    DefaultResponse(models::Errors),
    UnknownValue(serde_json::Value),
}

/// Collects from Globalcatalog the information about categories, subcategories (children), and services that belong to those categories.
pub async fn get_catalog_categories(
    configuration: &configuration::Configuration,
    x_request_id: Option<&str>,
    x_correlation_id: Option<&str>,
    translations_lang: Option<&str>,
) -> Result<models::CatalogCategories, Error<GetCatalogCategoriesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_x_request_id = x_request_id;
    let p_x_correlation_id = x_correlation_id;
    let p_translations_lang = translations_lang;

    let uri_str = format!(
        "{}/v3/resources/catalog_categories",
        configuration.base_path
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_translations_lang {
        req_builder = req_builder.query(&[("translations_lang", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_x_request_id {
        req_builder = req_builder.header("x-request-id", param_value.to_string());
    }
    if let Some(param_value) = p_x_correlation_id {
        req_builder = req_builder.header("x-correlation-id", param_value.to_string());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CatalogCategories`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CatalogCategories`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCatalogCategoriesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
