/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.23.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EstimatorV2InputPubsInner {
    Circuit(EstimatorV2InputCircuit),
    Observable(HashMap<String, f64>),
}

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EstimatorV2InputCircuit {
    pub __type__: String,
    pub __value__: String,
}

impl EstimatorV2InputCircuit {
    pub fn new(qpy_string: String) -> EstimatorV2InputCircuit {
        EstimatorV2InputCircuit {
            __type__: "QuantumCircuit".to_string(),
            __value__: qpy_string,
        }
    }
}
