/*
 * Global Search
 *
 * Search for resources with the global and shared resource properties repository that is integrated in the IBM Cloud platform. The search repository stores and searches cloud resources attributes, which categorize or classify resources. A resource is a physical or logical component that can be created or reserved for an application or service instance. They are owned by resource providers, such as IBM Kubernetes Service, or resource controller in IBM Cloud. Resources are uniquely identified by a Cloud Resource Name (CRN) or by an IMS ID. The properties of a resource include tags and system properties. Both properties are defined in an IBM Cloud billing account, and span across many regions.
 *
 * The version of the OpenAPI document: 2.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FirstCall : The request body when calling the first time the v3 search
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FirstCall {
    /// The Lucene-formatted query string. Default to '*' if not set
    #[serde(rename = "query")]
    pub query: String,
    /// The list of the fields returned by the search. By default, the returned fields are the `account_id`, `name`, `type`, `family`, and `crn`. For all queries, `crn` is always returned. You may set `\"fields\": [\"*\"]` to discover the set of fields available to request.
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<String>>,
}

impl FirstCall {
    /// The request body when calling the first time the v3 search
    pub fn new(query: String) -> FirstCall {
        FirstCall {
            query,
            fields: None,
        }
    }
}
