/*
 * Global Search
 *
 * Search for resources with the global and shared resource properties repository that is integrated in the IBM Cloud platform. The search repository stores and searches cloud resources attributes, which categorize or classify resources. A resource is a physical or logical component that can be created or reserved for an application or service instance. They are owned by resource providers, such as IBM Kubernetes Service, or resource controller in IBM Cloud. Resources are uniquely identified by a Cloud Resource Name (CRN) or by an IMS ID. The properties of a resource include tags and system properties. Both properties are defined in an IBM Cloud billing account, and span across many regions.
 *
 * The version of the OpenAPI document: 2.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GstData : A Global Search and Tagging service data information
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GstData {
    /// family
    #[serde(rename = "family")]
    pub family: String,
    /// types
    #[serde(rename = "types")]
    pub types: Vec<String>,
    /// service_name
    #[serde(rename = "service_name")]
    pub service_name: String,
}

impl GstData {
    /// A Global Search and Tagging service data information
    pub fn new(family: String, types: Vec<String>, service_name: String) -> GstData {
        GstData {
            family,
            types,
            service_name,
        }
    }
}
