/*
 * Global Search
 *
 * Search for resources with the global and shared resource properties repository that is integrated in the IBM Cloud platform. The search repository stores and searches cloud resources attributes, which categorize or classify resources. A resource is a physical or logical component that can be created or reserved for an application or service instance. They are owned by resource providers, such as IBM Kubernetes Service, or resource controller in IBM Cloud. Resources are uniquely identified by a Cloud Resource Name (CRN) or by an IMS ID. The properties of a resource include tags and system properties. Both properties are defined in an IBM Cloud billing account, and span across many regions.
 *
 * The version of the OpenAPI document: 2.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SearchBody : search body
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchBody {
    /// The query string
    #[serde(rename = "query")]
    pub query: Vec<String>,
    /// The list of the fields that are returned by the search. The CRN is always returned.
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Vec<String>>,
    /// An opaque token. Initially set to null or undefined, then passes the value that was returned by the previous call
    #[serde(
        rename = "token",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub token: Option<Option<String>>,
}

impl SearchBody {
    /// search body
    pub fn new(query: Vec<String>) -> SearchBody {
        SearchBody {
            query,
            fields: None,
            token: None,
        }
    }
}
