/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionControlsIdentities {
    #[serde(rename = "add")]
    pub add: bool,
    #[serde(rename = "remove")]
    pub remove: bool,
}

impl ActionControlsIdentities {
    pub fn new(add: bool, remove: bool) -> ActionControlsIdentities {
        ActionControlsIdentities { add, remove }
    }
}
