/*
 * IAM Identity Services
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateTemplateAssignmentRequest : Input body parameters for the Assignment update
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTemplateAssignmentRequest {
    /// Template version to be applied to the assignment. To retry all failed assignments, provide the existing version. To migrate to a different version, provide the new version number.
    #[serde(rename = "template_version")]
    pub template_version: i64,
}

impl UpdateTemplateAssignmentRequest {
    /// Input body parameters for the Assignment update
    pub fn new(template_version: i64) -> UpdateTemplateAssignmentRequest {
        UpdateTemplateAssignmentRequest { template_version }
    }
}
